name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Java 8 on the agent
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # Compile our application with Maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
   
    jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Other steps may be present
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Other steps may be present

      # Add the following steps for setting up JDK 8 and building with Maven
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
